# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180313_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.func_path_upload_gambar),
        ),
    ]
