# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penulis_komentar', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('isi_komentar', models.CharField(max_length=200)),
                ('publish_status', models.BooleanField(default=False)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel.Artikel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
