# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='kategori_artikel',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='penulis',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='artikel',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='penulis_komentar',
        ),
        migrations.DeleteModel(
            name='Kontak',
        ),
        migrations.DeleteModel(
            name='Penulis',
        ),
        migrations.DeleteModel(
            name='SettingWeb',
        ),
        migrations.DeleteModel(
            name='Artikel',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Komentar',
        ),
    ]
