# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_kontak'),
        ('homepage', '0002_auto_20180309_0730'),
    ]

    operations = [
    ]
