# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivasiEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('key', models.CharField(blank=True, max_length=120, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('forced_expired', models.BooleanField(default=False)),
                ('expires', models.IntegerField(default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='akun',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='aktivasiemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
