# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nama_lengkap',
            new_name='full_name',
        ),
    ]
