# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_auto_20180323_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivasiemail',
            name='expires',
            field=models.IntegerField(default=7),
        ),
    ]
