# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_auto_20180315_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='nama_lengkap',
        ),
    ]
