# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul_artikel', models.CharField(max_length=200)),
                ('isi_artikel', tinymce.models.HTMLField()),
                ('publish_status', models.BooleanField(default=False)),
                ('kategori_artikel', models.ManyToManyField(blank=True, null=True, related_name='kategori_related', to='kategori.Kategori')),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_artikel', models.ManyToManyField(blank=True, null=True, related_name='tag_related', to='tags.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
