# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
